<#
.SYNOPSIS
   Install a `grimvault` shim into C:\Users\<you>\.bin so the CLI is callable
   from any terminal.

.DESCRIPTION
   Writes a .cmd wrapper that forwards %* to a specific grimvault.exe path.
   The wrapper resolves to the real exe so Qt's adjacent-DLL discovery
   keeps working (the exe and its Qt6Core.dll, plugins/, etc. stay
   together; only the launcher lives on PATH).

   If C:\Users\<you>\.bin isn't on $env:Path, the script offers to add it
   to HKCU\Environment (user PATH).

.PARAMETER ExePath
   Absolute path to the grimvault.exe to forward to. Defaults to the
   freshly-built local debug binary.

.PARAMETER BinDir
   Directory the shim lives in. Defaults to C:\Users\<you>\.bin.

.PARAMETER AddToPath
   Add $BinDir to HKCU\Environment\Path without prompting.

.PARAMETER NoPrompt
   Never prompt; just skip the PATH edit if missing.

.EXAMPLE
   pwsh tools/install-cli.ps1
   pwsh tools/install-cli.ps1 -ExePath C:\path\to\grimvault.exe -AddToPath
#>

[CmdletBinding ()]
param (
   [string] $ExePath,
   [string] $BinDir = (Join-Path $env:USERPROFILE ".bin"),
   [switch] $AddToPath,
   [switch] $NoPrompt
)

$ErrorActionPreference = "Stop"

function Ok  ([string] $msg) { Write-Host "OK     $msg" -ForegroundColor Green }
function Inf ([string] $msg) { Write-Host "       $msg" -ForegroundColor DarkGray }
function Wrn ([string] $msg) { Write-Host "WARN   $msg" -ForegroundColor Yellow }
function Fail ([string] $msg) { Write-Host "FAIL   $msg" -ForegroundColor Red; exit 1 }

# ---- Resolve ExePath ------------------------------------------------------

if (-not $ExePath) {
   $repoRoot = (Resolve-Path "$PSScriptRoot\..").Path
   $ExePath  = Join-Path $repoRoot "build\windows-msvc-debug\grimvault.exe"
}

if (-not (Test-Path $ExePath)) {
   Fail @"
grimvault.exe not found at:
   $ExePath
Build it first (pwsh tools\dev-run.ps1 -NoRun) or pass -ExePath explicitly.
"@
}

$ExePath = (Resolve-Path $ExePath).Path
Ok "exe = $ExePath"

# ---- Ensure $BinDir exists ------------------------------------------------

if (-not (Test-Path $BinDir)) {
   New-Item -ItemType Directory -Path $BinDir | Out-Null
   Ok  "created $BinDir"
} else {
   Inf "bin dir already exists: $BinDir"
}

# ---- Write grimvault.cmd shim --------------------------------------------

$shim = Join-Path $BinDir "grimvault.cmd"

$shimBody = @"
@echo off
rem  Auto-generated by tools/install-cli.ps1. Forwards to the real exe so
rem  Qt's adjacent-DLL discovery resolves correctly. Re-run install-cli.ps1
rem  to update the target path.
"$ExePath" %*
"@

Set-Content -Path $shim -Value $shimBody -Encoding ASCII
Ok "wrote $shim"

# ---- PATH check -----------------------------------------------------------

$userPath = [Environment]::GetEnvironmentVariable("Path", "User")
$onPath   = ($userPath -split ';') -contains $BinDir

if ($onPath) {
   Ok "$BinDir is already on user PATH"
} else {
   $shouldAdd = $false
   if ($AddToPath) {
      $shouldAdd = $true
   } elseif (-not $NoPrompt) {
      Wrn "$BinDir is not on your user PATH."
      $reply = Read-Host "Add it to HKCU\Environment\Path now? [Y/n]"
      $shouldAdd = ($reply -eq '' -or $reply -match '^[yY]')
   } else {
      Wrn "$BinDir is not on user PATH; pass -AddToPath to add it."
   }

   if ($shouldAdd) {
      $newPath = if ($userPath) { "$userPath;$BinDir" } else { $BinDir }
      [Environment]::SetEnvironmentVariable("Path", $newPath, "User")
      Ok  "added $BinDir to user PATH (open a fresh shell to pick it up)"
   }
}

# ---- Smoke test in current shell -----------------------------------------

$env:PATH = "$BinDir;$env:PATH"
$where = Get-Command grimvault -ErrorAction SilentlyContinue
if ($where) {
   Ok "grimvault resolves to $($where.Source) in this shell"
} else {
   Wrn "grimvault did not resolve in this shell; open a fresh terminal."
}

Write-Host ""
Write-Host "Try it:" -ForegroundColor Cyan
Write-Host "   grimvault --help"
Write-Host "   grimvault status"
Write-Host "   grimvault login"
