# grimvault_write_env_header (<path>)
#
# Writes <path>/gv/core/env.h with constexpr per-env definitions for
# dev / qa / prod, plus a default selected by -DGRIMVAULT_ENV at configure
# time. Default is `prod` so a bare local build behaves like a production
# binary unless explicitly told otherwise (the dev-run.ps1 script passes
# -DGRIMVAULT_ENV=dev for local development).
#
# Per GrimVault MVP contract (docs/architecture/grimvault-mvp.md §10):
#
#   env  | client_id  | API host                  | Auth host                  | SPA host
#   -----+------------+---------------------------+----------------------------+--------------------
#   dev  | grimvault  | api.dev.darkerdb.com      | auth.dev.darkerdb.com      | dev.darkerdb.com
#   qa   | grimvault  | api.qa.darkerdb.com       | auth.qa.darkerdb.com       | qa.darkerdb.com
#   prod | grimvault  | api.darkerdb.com          | auth.darkerdb.com          | darkerdb.com
#
# Single OAuth client_id (`grimvault`) is used across all envs. PKCE +
# first-party + loopback redirect wildcard makes per-env client separation
# unnecessary until an incident-response need surfaces.
#
# Runtime env selection: the binary contains all three EnvDef structs.
# gv::core::resolve_active_env () picks one based on (in order):
#   1. `--env <name>` CLI flag
#   2. GRIMVAULT_ENV environment variable
#   3. The compile-time default (k_env_default).

set (GRIMVAULT_ENV "prod"
   CACHE STRING "Default deployment env: dev | qa | prod")
set_property (CACHE GRIMVAULT_ENV PROPERTY STRINGS dev qa prod)

if (NOT GRIMVAULT_ENV STREQUAL "dev" AND
    NOT GRIMVAULT_ENV STREQUAL "qa"  AND
    NOT GRIMVAULT_ENV STREQUAL "prod")
   message (FATAL_ERROR
      "GRIMVAULT_ENV must be one of: dev | qa | prod (got '${GRIMVAULT_ENV}')")
endif ()

if (GRIMVAULT_ENV STREQUAL "dev")
   set (_GV_API_BASE_URL  "https://api.dev.darkerdb.com")
   set (_GV_AUTH_BASE_URL "https://auth.dev.darkerdb.com")
   set (_GV_SPA_BASE_URL  "https://dev.darkerdb.com")
elseif (GRIMVAULT_ENV STREQUAL "qa")
   set (_GV_API_BASE_URL  "https://api.qa.darkerdb.com")
   set (_GV_AUTH_BASE_URL "https://auth.qa.darkerdb.com")
   set (_GV_SPA_BASE_URL  "https://qa.darkerdb.com")
else ()
   set (_GV_API_BASE_URL  "https://api.darkerdb.com")
   set (_GV_AUTH_BASE_URL "https://auth.darkerdb.com")
   set (_GV_SPA_BASE_URL  "https://darkerdb.com")
endif ()

function (grimvault_write_env_header out_path)
   set (template
[=[
#pragma once

// Generated by cmake/Env.cmake. Default env (compile time): @GRIMVAULT_ENV@.
// Do not edit by hand. Override the compile-time default with:
//    cmake --preset windows-msvc-debug -DGRIMVAULT_ENV=dev
// or override at runtime via --env <name> / GRIMVAULT_ENV=<name>.

#include <string_view>

namespace gv::core {

struct EnvDef {
   std::string_view name;
   std::string_view client_id;
   std::string_view api_base_url;
   std::string_view auth_base_url;
   std::string_view spa_base_url;
};

inline constexpr EnvDef k_env_dev {
   .name          = "dev",
   .client_id     = "grimvault",
   .api_base_url  = "https://api.dev.darkerdb.com",
   .auth_base_url = "https://auth.dev.darkerdb.com",
   .spa_base_url  = "https://dev.darkerdb.com",
};

inline constexpr EnvDef k_env_qa {
   .name          = "qa",
   .client_id     = "grimvault",
   .api_base_url  = "https://api.qa.darkerdb.com",
   .auth_base_url = "https://auth.qa.darkerdb.com",
   .spa_base_url  = "https://qa.darkerdb.com",
};

inline constexpr EnvDef k_env_prod {
   .name          = "prod",
   .client_id     = "grimvault",
   .api_base_url  = "https://api.darkerdb.com",
   .auth_base_url = "https://auth.darkerdb.com",
   .spa_base_url  = "https://darkerdb.com",
};

inline constexpr const EnvDef& k_env_default = k_env_@GRIMVAULT_ENV@;

// Legacy aliases — pre-runtime-env-resolution callers reach for these.
// New code should pull from the resolved EnvDef returned by
// gv::core::resolve_active_env (). These mirror the compile-time default.
constexpr const char* env           = "@GRIMVAULT_ENV@";
constexpr const char* client_id     = "grimvault";
constexpr const char* api_base_url  = "@_GV_API_BASE_URL@";
constexpr const char* auth_base_url = "@_GV_AUTH_BASE_URL@";
constexpr const char* spa_base_url  = "@_GV_SPA_BASE_URL@";

} // namespace gv::core
]=])

   string (CONFIGURE "${template}" rendered @ONLY)

   file (WRITE "${out_path}.tmp" "${rendered}")
   configure_file ("${out_path}.tmp" "${out_path}" COPYONLY)
   file (REMOVE "${out_path}.tmp")
endfunction ()
