# grimvault_write_env_header (<path>)
#
# Writes <path>/gv/core/env.h with constexpr per-env constants (OAuth
# client_id + API base URL). CI overrides via -DGRIMVAULT_ENV=dev|qa|prod
# at configure time. Default is `prod` so a bare local build behaves like
# a production binary unless explicitly told otherwise.
#
# Per GrimVault MVP contract (docs/architecture/grimvault-mvp.md §10):
#
#   env  | client_id  | API base URL
#   -----+------------+---------------------------------
#   dev  | grimvault  | https://api.dev.darkerdb.com
#   qa   | grimvault  | https://api.qa.darkerdb.com
#   prod | grimvault  | https://api.darkerdb.com
#
# Single OAuth client_id (`grimvault`) is used across all envs. PKCE +
# first-party + loopback redirect wildcard makes per-env client separation
# unnecessary until an incident-response need surfaces.
#
# The values are baked at compile time. No runtime override in shipped
# builds; dev builds can ship a `--env` flag that the engineer wires
# separately.

set (GRIMVAULT_ENV "prod"
   CACHE STRING "Deployment env: dev | qa | prod")
set_property (CACHE GRIMVAULT_ENV PROPERTY STRINGS dev qa prod)

# Validate up front so a typo at -D fails the configure step, not the runtime.
if (NOT GRIMVAULT_ENV STREQUAL "dev" AND
    NOT GRIMVAULT_ENV STREQUAL "qa"  AND
    NOT GRIMVAULT_ENV STREQUAL "prod")
   message (FATAL_ERROR
      "GRIMVAULT_ENV must be one of: dev | qa | prod (got '${GRIMVAULT_ENV}')")
endif ()

# Single OAuth client across all envs. Only the API/SPA base URLs vary.
set (_GV_CLIENT_ID "grimvault")

if (GRIMVAULT_ENV STREQUAL "dev")
   set (_GV_API_BASE_URL "https://api.dev.darkerdb.com")
   set (_GV_SPA_BASE_URL "https://dev.darkerdb.com")
elseif (GRIMVAULT_ENV STREQUAL "qa")
   set (_GV_API_BASE_URL "https://api.qa.darkerdb.com")
   set (_GV_SPA_BASE_URL "https://qa.darkerdb.com")
else ()
   set (_GV_API_BASE_URL "https://api.darkerdb.com")
   set (_GV_SPA_BASE_URL "https://darkerdb.com")
endif ()

function (grimvault_write_env_header out_path)
   set (template
[=[
#pragma once

// Generated by cmake/Env.cmake from GRIMVAULT_ENV=@GRIMVAULT_ENV@.
// Do not edit by hand. Override at configure time:
//    cmake --preset release-windows -DGRIMVAULT_ENV=dev

namespace gv::core {

constexpr const char* env          = "@GRIMVAULT_ENV@";
constexpr const char* client_id    = "@_GV_CLIENT_ID@";
constexpr const char* api_base_url = "@_GV_API_BASE_URL@";
constexpr const char* spa_base_url = "@_GV_SPA_BASE_URL@";

} // namespace gv::core
]=])

   string (CONFIGURE "${template}" rendered @ONLY)

   file (WRITE "${out_path}.tmp" "${rendered}")
   configure_file ("${out_path}.tmp" "${out_path}" COPYONLY)
   file (REMOVE "${out_path}.tmp")
endfunction ()
